source 'https://rubygems.org'

gem 'guard-rspec', require: false

gem "pry"
gem 'pry-remote'
gem "pry-stack_explorer"
gem "pry-debugger"

# group :development, :test do
#   gem 'actionpack'
#   gem 'railties'
#   gem 'tzinfo'

#   gem 'thin'

#   gem 'jasminerice'
#   gem 'jquery-rails'
#   gem 'guard-jasmine'
# end
